// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRV77ZK9T4E1ejsqUgL0U68TVjwuGtAgI',
    appId: '1:519421115177:web:927acd641d2540dc105538',
    messagingSenderId: '519421115177',
    projectId: 'speedify-1084e',
    authDomain: 'speedify-1084e.firebaseapp.com',
    databaseURL: 'https://speedify-1084e-default-rtdb.firebaseio.com',
    storageBucket: 'speedify-1084e.firebasestorage.app',
    measurementId: 'G-G0MRYP9EZL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkIupnhD8iGI-SoIdcftSlOGJoA2jxCqY',
    appId: '1:519421115177:android:acb02bdfedb005a7105538',
    messagingSenderId: '519421115177',
    projectId: 'speedify-1084e',
    databaseURL: 'https://speedify-1084e-default-rtdb.firebaseio.com',
    storageBucket: 'speedify-1084e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK1o4dEEgoxGX2-_qNNVPkzi7o8Tg8518',
    appId: '1:519421115177:ios:535a7f0c5d90bb4a105538',
    messagingSenderId: '519421115177',
    projectId: 'speedify-1084e',
    databaseURL: 'https://speedify-1084e-default-rtdb.firebaseio.com',
    storageBucket: 'speedify-1084e.firebasestorage.app',
    iosBundleId: 'com.example.speedify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDK1o4dEEgoxGX2-_qNNVPkzi7o8Tg8518',
    appId: '1:519421115177:ios:535a7f0c5d90bb4a105538',
    messagingSenderId: '519421115177',
    projectId: 'speedify-1084e',
    databaseURL: 'https://speedify-1084e-default-rtdb.firebaseio.com',
    storageBucket: 'speedify-1084e.firebasestorage.app',
    iosBundleId: 'com.example.speedify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRV77ZK9T4E1ejsqUgL0U68TVjwuGtAgI',
    appId: '1:519421115177:web:992a91d6327e7571105538',
    messagingSenderId: '519421115177',
    projectId: 'speedify-1084e',
    authDomain: 'speedify-1084e.firebaseapp.com',
    databaseURL: 'https://speedify-1084e-default-rtdb.firebaseio.com',
    storageBucket: 'speedify-1084e.firebasestorage.app',
    measurementId: 'G-F2HQDY9Y49',
  );
}
